It's easy to gain a thousand, ten thousand or even a hundred thousand followers on Twitter.

JK Moligna made a lot of money guaranteeing 10,000 followers to anyone who bought into his program, and he's not alone.

There are plenty of people out there charging CEOs and aspiring influencers $10,000 for 10,000 followers. 

Now that might seem like a lot of money, but it's worth it.

Just take @Chrisstaud and @Nikkisiapno. They used the best techniques in the Twitter Growth playbook to gain over 100,000 followers in less than a year, and they are now boasting of scaling their monthly monetization from $5000 a month to $20,000 a month.

There is a lot of money to be made on Twitter if you can grow followers and flame the fires of engagement. And it's not hard to do if you know the tricks.

The thing is, the accounts that grow using things like engagement groups, ghost writers, swipe files and recycled content don't want you to know about the tricks they use.

- Ghostwriters can make over a million dollars a year, so they will fight ruthlessly to protect their business model.

- Influencers who grew using tricks and shady tactics would lose influence if people realized their growth wasn't orgainic.

- Shysters who peddle fake 'twitter growth advice' would lose their business if people knew they didn't gain their followings honestly.

I personally have taken a lot of blowback for exposing the shady and unethical practices the biggest accounts on TechTwitter have used to grow. These people are ruthless when it comes to protecting their investments.

But I can be ruthless at exposing the truth, and that's what I plan to do here. Just be honest and truthful with you about how the biggest accounts in the fitness, technology, entreprenuership and self-improvement sectors grew their following.

The truth is always a great shield when the dishonest among us ruthlessly attack.

== Swipe Files

Selling Twitter growth advice is a hundred million dollar industry.

It's an easy industry to get into. Just open a Twitter account, use some Twitter growth tactics to quickly gain 10,000 or 20,000 followers, and then use that quick growth to sell a Gumroad product or Udemy course.

Of course, the people selling those products don't tell you what they really did to gain followers. Instead, they just rehash the same standard set of Twitter growth advice that is filled with lies, half-truth and strategies that quite frankly don't work.

I purchased a lot of Twitter growth courses, did extensive reading online and paid close attention every time a big account's ghostwriter wrote a thread about how to gain followers online. The advice was always the same:

- Tweet at least twice a day
- Interact and engage with people
- Undertweet the biggest accounts
- Optimize your profile
- Niche down into a subgenre
- Use hashtags effectively
- Craft original threads with unique hooks

I'm here to tell you none of that stuff works, and the big Twitter accounts taking money off people and feeding them this ineffective advice know it doesn't work.

Don't get me wrong, if you follow this advice you're likely to add a few followers a day. 

For new, organic accounts with less than 1000 followers, an amazing ratio of tweets to followers gained is 10 to 1. 

That means if you follow this advice and do 10 tweets and replies every day, you'll gain 7 followers a week.

In a month you might get lucky and gain 50.

In a year your ratio might improve or you might get a viral tweet and you'll grow to over 1000 followers.

And that's assuming you maintain a consistent, never-ending pace of 10 original and compelling tweets and replies a week.

It's an unsustainable pace, and the payback isn't worth the effort. It'd take 10 years at that pace to gain 10,000 followers.

The advice simply doesn't work, and if you investigate the big Twitter accounts selling this advice, you'll quickly realize they don't eat their own dog food. These are not the techniques they used to grow thier following.

By the way, that ratio will change over time. As your account grows to over 10,000 followers, the ratio of tweets to followers improves. 

Two established, organic accounts I respect greatly are @vlad_mihalcea and @starbuxman.

- Vlad is a power Twitter user and has 70K followers on 50K tweets, so it's just better than a 1:1 ratio
- Josh (@starbuxman) has 70K followers on 100K tweets, a ratio of 0.7:1

In contrast, @Nikkisiapno in her first year on Twitter gained 125K followers on only 7000 tweets, a ration of 17:1. 

Ratios that high should raise an eyebrow. I guarantee you will never get 17 followers for every one tweet following the Twitter growth advice specified above.

=== The 'Tweet Twice a Day' Myth

Every Twitter growth guru starts off by saying you have to tweet every single day, if not twice a day.

On the surface that's good advice. I mean, you can't hit a baseball out of the park if you don't step up to the plate. So I agree that to grow on Twitter you need to tweet. It's what the big Twitter growth experts leave out of that piece of advice that's important.

First, you need to know that the big accounts are not actually logging into Twitter every day and publishing tweets. They all use scheduling and automation tools.

The big TechTwitter accounts spend an afternoon every couple of months and schedule 30 to 60 days worth of tweets. They then close down their automation tool and let it run. It sends out two or three tweets a day for them and they don't have to worry about their daily cadence.

That shouldn't be a huge revelation. It just makes sense that if you're a Twitter power user you'd use a scheduling tool. But when I was new to Twitter I had no idea about things like FeedHive and TweetHunter. I thought everyone was logging in every day and diligently tweeting out from their laptop or their cellphone. I had no idea that the big accounts just clicked play on their scheduling tool at the start of every quarter.

Again, the use of scheduling tools to tweet every day isn't a huge revelation, but I do think it's noteworthy that all the Twitter Growth gurus tend to fail to mention it. But I understand why. The big influencers would lose their authenticity if people knew that it was a scheduling tool sending out all of those engagement tweets, making it look like they were active on the platform, all while they're on vacation somewhere rolling around in all the money they made selling Twitter growth courses to people.

Now the second issue I have with the 'tweet twice a day' advice is a lot more interesting than the first.

Implicit in the 'tweet twice a day' advice is the idea that you'd be producing original, engageing content, right? 

Wrong.

The biggest growth accounts on Twitter don't tweet out _original_ content every day. Instead, they just create 30 or 60 days of content and just put that all on repeat.

When I first got serious about Twitter, I had no idea how I was going to come up with two original tweets a day, 60 original tweets a month and over 700 original tweets a year. And I was certainly amazed at how all the fastest growing accounts on Twitter managed to maintain that pace. The fact is, they don't.

So that's one of the biggest tricks, and one of the most tightly guarded secrets, in the TechTwitter community.

Twitter users have a short memory, so there's no need to post original content. Just put together 60 days worth of tweets and then just click rewind and play every two months, and every time you do it you're 10,000 followers richer.

Just go to any of the fastest growing accounts in your favorite genre, look at some of their most popular tweets and do a search for that tweet under that account. 

This search on MadzaDev for his '8 Free online courses' tweet shows the exact same thing was tweeted out on:

- March 5th
- January 6th
- December 3rd
- November 1st

As you can see, the same tweet went out at pretty much the same time every month.




 




















