It's easy to gain a thousand, ten thousand or even a hundred thousand followers on Twitter.

JK Moligna made a lot of money guaranteeing 10,000 followers to anyone who bought into his program, and he's not alone.

There are plenty of people out there charging CEOs and aspiring influencers $10,000 for 10,000 followers. 

Now that might seem like a lot of money, but it's worth it.

Just take @Chrisstaud and @Nikkisiapno. They used the best techniques in the Twitter Growth playbook to gain over 100,000 followers in less than a year, and they are now boasting of scaling their monthly monetization from $5000 a month to $20,000 a month.

There is a lot of money to be made on Twitter if you can grow followers and flame the fires of engagement. And it's not hard to do if you know the tricks.

The thing is, the accounts that grow using things like engagement groups, ghost writers, swipe files and recycled content don't want you to know about the tricks they use.

- Ghostwriters can make over a million dollars a year, so they will fight ruthlessly to protect their business model.

- Influencers who grew using tricks and shady tactics would lose influence if people realized their growth wasn't orgainic.

- Shysters who peddle fake 'twitter growth advice' would lose their business if people knew they didn't gain their followings honestly.

I personally have taken a lot of blowback for exposing the shady and unethical practices the biggest accounts on TechTwitter have used to grow. These people are ruthless when it comes to protecting their investments.

But I can be ruthless at exposing the truth, and that's what I plan to do here. Just be honest and truthful with you about how the biggest accounts in the fitness, technology, entreprenuership and self-improvement sectors grew their following.

The truth is always a great shield when the dishonest among us ruthlessly attack.

== Swipe Files

Selling Twitter growth advice is a hundred million dollar industry.

It's an easy industry to get into. Just open a Twitter account, use some Twitter growth tactics to quickly gain 10,000 or 20,000 followers, and then use that quick growth to sell a Gumroad product or Udemy course.

Of course, the people selling those products don't tell you what they really did to gain followers. Instead, they just rehash the same standard set of Twitter growth advice that is filled with lies, half-truth and strategies that quite frankly don't work.

I purchased a lot of Twitter growth courses, did extensive reading online and paid close attention every time a big account's ghostwriter wrote a thread about how to gain followers online. The advice was always the same:

- Tweet at least twice a day
- Interact and engage with people
- Undertweet the biggest accounts
- Optimize your profile
- Niche down into a subgenre
- Use hashtags effectively
- Craft original threads with unique hooks

I'm here to tell you none of that stuff works, and the big Twitter accounts taking money off people and feeding them this ineffective advice know it doesn't work.

Don't get me wrong, if you follow this advice you're likely to add a few followers a day. 

For new, organic accounts with less than 1000 followers, an amazing ratio of tweets to followers gained is 10 to 1. 

That means if you follow this advice and do 10 tweets and replies every day, you'll gain 7 followers a week.

In a month you might get lucky and gain 50.

In a year your ratio might improve or you might get a viral tweet and you'll grow to over 1000 followers.

And that's assuming you maintain a consistent, never-ending pace of 10 original and compelling tweets and replies a week.

It's an unsustainable pace, and the payback isn't worth the effort. It'd take 10 years at that pace to gain 10,000 followers.

The advice simply doesn't work, and if you investigate the big Twitter accounts selling this advice, you'll quickly realize they don't eat their own dog food. These are not the techniques they used to grow thier following.


















